./aipsetup-2009.01.26.10.02.tar.lzma --------------------------------------------------------------- revno: 22 committer: agu <agu@agutilities> branch nick: repo timestamp: Thu 2010-07-01 22:10:18 +0300

diff --git a/_aipb_fpbf b/_aipb_fpbf
--- a/_aipb_fpbf
+++ b/_aipb_fpbf
@@ -1,5 +1,16 @@
 #!/bin/bash
-cd /var/log/packages
+
+if [ ! -d "$AIP_DIR" ]
+then
+    echo " SORRY: please, install aipsetup (if not yet),"
+    echo "        and run 'remove' from main program (aipsetup)"
+    echo " ERROR: AIP_DIR not set"
+    exit 1
+fi
+
+. "$AIP_DIR/_aipb_init"
+
+cd "$PKG_INFO/sums"
 find -maxdepth 1 -name '*.bz2' -exec bash -c " cat '{}' |  bzip2 -d | grep '$1' ; e=\$? ; if [ \$e -eq 0 ] ; then echo -e 'found $1 in: {}\n' ; fi  " ';'
 echo "search complite"
 exit 0
