./aipsetup-2009.02.21.20.14.tar.bz2 --------------------------------------------------------------- revno: 40 committer: agu <agu@agutilities> branch nick: repo timestamp: Thu 2010-07-01 22:10:49 +0300

diff --git a/_aipb_install b/_aipb_install
--- a/_aipb_install
+++ b/_aipb_install
@@ -2,7 +2,8 @@
 
 if [ ! -d "$AIP_DIR" ]
 then
-    echo " SORRY: please, install aipsetup (if not yet), and run 'install' from main program (aipsetup)"
+    echo " SORRY: please, install aipsetup (if not yet),"
+    echo "        and run 'install' from main program (aipsetup)"
     echo " ERROR: AIP_DIR not set"
     exit 1
 fi
@@ -20,7 +21,26 @@ for i in $*
 do
     if [ -f "$i" ]
     then
-	printf "installing: "$i":"
+	printf "installing: \"$i\"...\n"
+	printf "     md5:"
+	md5sum -c "$i".md5
+	if [ $? -ne 0 ]
+	then
+	    echo "error"
+	    ERi=$(( $ERi + 1 ))
+	    continue
+	fi
+
+	printf "  sha512:"
+	sha512sum -c "$i".sha512
+	if [ $? -ne 0 ]
+	then
+	    echo "error"
+	    ERi=$(( $ERi + 1 ))
+	    continue
+	fi
+
+	echo -n "      installing:"
 	bash "$AIP_DIR/_aipb_extract" "$i" "$DESTDIR"/
 	if [ $? -eq 0 ]
 	then
diff --git a/_aipb_list b/_aipb_list
--- a/_aipb_list
+++ b/_aipb_list
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -f
+
 if [ ! -d "$AIP_DIR" ]
 then
     echo " SORRY: please, install aipsetup (if not yet),"
@@ -10,15 +12,23 @@ fi
 
 . "$AIP_DIR/_aipb_init"
 
-cd "$PKG_INFO/sums"
+cd "$PKG_INFO"
 
 if [ $? -eq 0 ]
 then
-    LIST=`find -maxdepth 1 -type f -name '*.bz2' | sort `
-
+    if [ -z "$1" ]
+    then
+	LIST=`find -maxdepth 1 -type f -name '*.bz2' | sort `
+    else
+	set -f
+	LIST=`find -maxdepth 1 -type f -name "$1" | sort `
+    fi
     for i in $LIST
     do
-	ls -l $i
+	stat --printf="%n \t Changed: \"%z\"\n" $i
     done
+else
+    echo "can't cd to packages dir"
+    exit 1
 fi
 exit 0
