./aipsetup-2009.10.31.16.45.tar.xz --------------------------------------------------------------- revno: 105 committer: agu <agu@agutilities> branch nick: repo timestamp: Thu 2010-07-01 22:13:17 +0300

diff --git a/_aipb_move_bzip2_to_xz_pk b/_aipb_move_bzip2_to_xz_pk
--- a/_aipb_move_bzip2_to_xz_pk
+++ b/_aipb_move_bzip2_to_xz_pk
@@ -35,6 +35,11 @@ do
     mkdir -p "$tmpdir_pkgname"
 
     bash "$AIP_DIR/_aipb_install" -b "$tmpdir_pkgname" "$i"
+    if [ "$?" -ne 0 ]
+    then
+	echo "can't unpack file"
+	continue
+    fi
     
     bash "$AIP_DIR/_aipb_move_bzip2_to_xz" -b "$tmpdir_pkgname" <<EOF
 yes
