./aipsetup-2009.01.26.10.06.tar.lzma --------------------------------------------------------------- revno: 24 committer: agu <agu@agutilities> branch nick: repo timestamp: Thu 2010-07-01 22:10:21 +0300

diff --git a/_aipb_checksums b/_aipb_checksums
--- a/_aipb_checksums
+++ b/_aipb_checksums
@@ -20,8 +20,15 @@ check() {
     fi
 
     cat "$PKG_INFO/sums/$check_p1" | bzip2 -d | sha512sum -c 
-
-    return $?
+    
+    if [ $? -eq 0 ]
+    then
+	echo " all ok"
+	return 0
+    else
+	echo " errors found"
+	return 1
+    fi
 }
 
 if [ ! -d "$AIP_DIR" ]
