./aipsetup-2009.01.26.09.22.tar.lzma --------------------------------------------------------------- revno: 21 committer: agu <agu@agutilities> branch nick: repo timestamp: Thu 2010-07-01 22:10:16 +0300

diff --git a/_aipb_extract b/_aipb_extract
--- a/_aipb_extract
+++ b/_aipb_extract
@@ -1,5 +1,21 @@
 #!/bin/bash
 
+if [ ! -d "$AIP_DIR" ]
+then
+    echo " SORRY: please, install aipsetup (if not yet),"
+    echo "        and run 'remove' from main program (aipsetup)"
+    echo " ERROR: AIP_DIR not set"
+    exit 1
+fi
+
+if [ ! -f "$AIP_DIR/_aipb_getarchtype" ]
+then
+    echo " ERROR: can't find [$AIP_DIR/_aipb_getarchtype]"
+    exit 1
+fi
+
+FILENAME="$1"
+
 if [ ! -d "$2" ]
 then
     DESTDIR='.'
@@ -7,86 +23,54 @@ else
     DESTDIR="$2"
 fi
 
-if [ -f "$1" ]
+if [ -f "$FILENAME" ]
 then
-    ARCH_TYPE=
-#     echo "extracting $1"
+    ARCH_TYPE=`bash "$AIP_DIR/_aipb_getarchtype" "$FILENAME"`
 
-    echo "$1" | grep -e '^.*\.tar\.gz$' > /dev/null 2>&1
     if [ $? -eq 0 ]
     then
-	ARCH_TYPE="tar.gz"
+	case $ARCH_TYPE in
+	    'tar.gz' | 'tgz')
+		set -o pipefail
+		cat "$FILENAME" | gzip -d | tar -xC "$DESTDIR"
+		set +o pipefail
+		fail=$?
+		;;
+	    'tar.bz2')
+		set -o pipefail
+		cat "$FILENAME" | bzip2 -d | tar -xC "$DESTDIR"
+		set +o pipefail
+		fail=$?
+		;;
+	    'tar.lzma')
+		set -o pipefail
+		cat "$FILENAME" | lzma -d | tar -xC "$DESTDIR"
+		set +o pipefail
+		fail=$?
+		;;
+	    'tar.7z')
+		set -o pipefail
+		7z x -so "$FILENAME" | tar -xC "$DESTDIR"
+		set +o pipefail
+		fail=$?
+		;;
+	    'zip')
+		unzip -qq "$FILENAME" -d "$DESTDIR"
+		fail=$?
+		;;
+	    *)
+		echo "unknown extention"
+		exit 1
+		;;
+	esac
+	if [ "$fail" -ne 0 ]
+	then
+	    echo "file extraction error"
+	fi
+	exit $fail
+    else
+	echo "unknown extention"
     fi
-
-    echo "$1" | grep -e '^.*\.tar\.bz2$' > /dev/null 2>&1
-    if [ $? -eq 0 ]
-    then
-	ARCH_TYPE="tar.bz2"
-    fi
-    
-    echo "$1" | grep -e '^.*\.tar\.lzma$' > /dev/null 2>&1
-    if [ $? -eq 0 ]
-    then
-	ARCH_TYPE="tar.lzma"
-    fi
-
-    echo "$1" | grep -e '^.*\.tgz$' > /dev/null 2>&1
-    if [ $? -eq 0 ]
-    then
-	ARCH_TYPE="tar.gz"
-    fi
-
-    echo "$1" | grep -e '^.*\.tar\.7z$' > /dev/null 2>&1
-    if [ $? -eq 0 ]
-    then
-	ARCH_TYPE="tar.7z"
-    fi
-
-    echo "$1" | grep -e '^.*\.zip$' > /dev/null 2>&1
-    if [ $? -eq 0 ]
-    then
-	ARCH_TYPE="zip"
-    fi
-
-    case $ARCH_TYPE in
-	'tar.gz')
-	    set -o pipefail
-	    cat "$1" | gzip -d | tar -xC "$DESTDIR"
-	    set +o pipefail
-	    fail=$?
-	    ;;
-	'tar.bz2')
-	    set -o pipefail
-	    cat "$1" | bzip2 -d | tar -xC "$DESTDIR"
-	    set +o pipefail
-	    fail=$?
-	    ;;
-	'tar.lzma')
-	    set -o pipefail
-	    cat "$1" | lzma -d | tar -xC "$DESTDIR"
-	    set +o pipefail
-	    fail=$?
-	    ;;
-	'tar.7z')
-	    set -o pipefail
-	    7z x -so "$1" | tar -xC "$DESTDIR"
-	    set +o pipefail
-	    fail=$?
-	    ;;
-	'zip')
-	    unzip -qq "$1" -d "$DESTDIR"
-	    fail=$?
-	    ;;
-	*)
-	    echo "unknown extention"
-	    exit 1
-	    ;;
-    esac
-    if [ "$fail" -ne 0 ]
-    then
-	echo "file extraction error"
-    fi
-    exit $fail
 else
     echo "file not exists"
 fi
diff --git a/_aipb_list b/_aipb_list
--- a/_aipb_list
+++ b/_aipb_list
@@ -1,5 +1,17 @@
 #!/bin/bash
 
+if [ ! -d "$AIP_DIR" ]
+then
+    echo " SORRY: please, install aipsetup (if not yet),"
+    echo "        and run 'remove' from main program (aipsetup)"
+    echo " ERROR: AIP_DIR not set"
+    exit 1
+fi
+
+. "$AIP_DIR/_aipb_init"
+
+cd "$PKG_INFO/sums"
+
 if [ $? -eq 0 ]
 then
     LIST=`find -maxdepth 1 -type f -name '*.bz2' | sort `
diff --git a/_aipb_pack b/_aipb_pack
--- a/_aipb_pack
+++ b/_aipb_pack
@@ -1,5 +1,21 @@
 #!/bin/bash
 
+
+if [ ! -d "$AIP_DIR" ]
+then
+    echo " SORRY: please, install aipsetup (if not yet),"
+    echo "        and run 'remove' from main program (aipsetup)"
+    echo " ERROR: AIP_DIR not set"
+    exit 1
+fi
+
+if [ ! -f "$AIP_DIR/_aipb_pksums" ]
+then
+    echo " ERROR: can't find [$AIP_DIR/_aipb_pksums]"
+    exit 1
+fi
+
+
 echo 'changing owner'
 chown -R root.root *
 echo 'changing rules'
@@ -11,25 +27,22 @@ PKGNAME=`basename $PPWD`
 FILEDIR=./var/log/packages
 FILELIST="$FILEDIR/$PKGNAME"
 
-# rm ./*.tar.bz2 > /dev/null 2> /dev/null
-# rm ./*.tar.bz2.md5 > /dev/null 2> /dev/null
-# rm ./*.tar.bz2.sha512 > /dev/null 2> /dev/null
-
 echo "Creating package: $PKGNAME..."
-echo "  creating installed file list"
+# echo "  creating installed file list"
 mkdir -p "$FILEDIR" > /dev/null 2> /dev/null
 rm  "$FILEDIR"/* > /dev/null 2> /dev/null
 
-touch "$FILELIST"
-find -type f | sed -e "s/$PKGNAME\$/$PKGNAME.bz2\n/" >> "$FILELIST"
-find -type l >> "$FILELIST"
-#echo "$FILEDIR/$PKGNAME.bz2" >> "$FILELIST"
+# touch "$FILELIST"
+# find ./ -type f ! -regex '.*/var/log/packages/.*' | sed -e "s/^\.//g"  >> "$FILELIST"
+# find ./ -type l ! -regex '.*/var/log/packages/.*'| sed -e "s/^\.//g" >> "$FILELIST"
 
-cat "$FILELIST" | sort > "$FILELIST"1
-cat "$FILELIST"1 > "$FILELIST"
-rm "$FILELIST"1
+# cat "$FILELIST" | sort > "$FILELIST"1
+# cat "$FILELIST"1 > "$FILELIST"
+# rm "$FILELIST"1
 
-bzip2 -9 "$FILELIST"
+# bzip2 -9 "$FILELIST"
+
+bash "$AIP_DIR/_aipb_pksums"
 
 
 mkdir ../pack > /dev/null 2> /dev/null
diff --git a/_aipb_remove b/_aipb_remove
--- a/_aipb_remove
+++ b/_aipb_remove
@@ -1,20 +1,67 @@
 #!/bin/bash
 
-if [ ! -f "$1" ]
+PPWD=`pwd`
+
+remove_p1=
+remove() {
+    
+    if [ ! -f "$PKG_INFO/sums/$remove_p1" ]
+    then
+	echo " ERROR: file $PKG_INFO/sums/$remove_p1 not found"
+	return 1
+    fi
+    basename "$remove_p1" .bz2
+    if [ $? -ne 0 ]
+    then
+	echo " ERROR: wrong checksum file"
+	return 1
+    fi
+    remove_line_count=`cat "$PKG_INFO/sums/$remove_p1" | bzip2 -d | wc -l`
+    remove_i=1
+    remove_all_removed=1
+    while [ "$remove_i" -ne "$remove_line_count" ]
+    do
+	FILENAME=`cat "$PKG_INFO/sums/$remove_p1" | bzip2 -d | sed -ne "$remove_i{p;q}" | sed -e "s/.*\*/$DESTDIR/g"`
+	cat "$PKG_INFO/sums/$remove_p1" | bzip2 -d | sed -ne "$remove_i{p;q}" | sha512sum -c > /dev/null 2>&1
+	if [ $? -eq 0 ]
+	then
+	    echo -e "rm \"$FILENAME\""
+	    rm "$FILENAME"
+	else
+	    remove_all_removed=0
+	fi
+	remove_i=$(( $remove_i + 1 ))
+    done
+    if [ $remove_all_removed -eq 1 ]
+    then
+	rm "$PKG_INFO/sums/$remove_p1"
+    fi
+    return 0
+}
+
+if [ ! -d "$AIP_DIR" ]
 then
-    echo "*** $1 does not exists"
+    echo " SORRY: please, install aipsetup (if not yet),"
+    echo "        and run 'remove' from main program (aipsetup)"
+    echo " ERROR: AIP_DIR not set"
     exit 1
 fi
 
-echo "removing $1"
+. "$AIP_DIR/_aipb_init"
 
-PPWD=`pwd`
+if [ -n "$DESTDIR" -a ! -a "$DESTDIR" ]
+then
+    echo "*** DESTDIR is set, but does not exists"
+    exit 1
+fi
 
-FILES=`cat $1 | bzip2 -d | sed -e "/^.*:.*&/d"`
+if [ -n "$DESTDIR" -a ! -d "$DESTDIR" ]
+then
+    echo "*** DESTDIR is set, exists, but isn't directory"
+    exit 1
+fi
 
-for i in $FILES
-do
-    rm -v "/$i"
-done
-
-exit 0
+remove_p1="$1"
+remove
+     
+exit $?
