./aipsetup-2009.10.31.12.55.tar.bz2 --------------------------------------------------------------- revno: 95 committer: agu <agu@agutilities> branch nick: repo timestamp: Thu 2010-07-01 22:12:50 +0300

diff --git a/_aipb_checksums b/_aipb_checksums
--- a/_aipb_checksums
+++ b/_aipb_checksums
@@ -2,6 +2,14 @@
 
 #!/bin/bash
 
+if [ ! -d "$AIP_DIR" ]
+then
+    echo " SORRY: please, install aipsetup (if not yet),"
+    echo "        and run this from main program (aipsetup)"
+    echo " ERROR: AIP_DIR not set"
+    exit 1
+fi
+
 PPWD=`pwd`
 
 check_p1=
diff --git a/_aipb_finddeps b/_aipb_finddeps
--- a/_aipb_finddeps
+++ b/_aipb_finddeps
@@ -3,6 +3,15 @@
 # this script looking for files, openable by ldd, depenfing on given
 # file
 
+
+if [ ! -d "$AIP_DIR" ]
+then
+    echo " SORRY: please, install aipsetup (if not yet),"
+    echo "        and run this from main program (aipsetup)"
+    echo " ERROR: AIP_DIR not set"
+    exit 1
+fi
+
 filename=$1
 theretosearch=$2
 
diff --git a/_aipb_getarchtype b/_aipb_getarchtype
--- a/_aipb_getarchtype
+++ b/_aipb_getarchtype
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+if [ ! -d "$AIP_DIR" ]
+then
+    echo " SORRY: please, install aipsetup (if not yet),"
+    echo "        and run this from main program (aipsetup)"
+    echo " ERROR: AIP_DIR not set"
+    exit 1
+fi
+
 ARCH_TYPE=
 FILENAME="$1"
 
@@ -49,6 +57,12 @@ echo "$FILENAME" | grep -e '^.*\.tar\.lzma$' > /dev/null 2>&1
 if [ $? -eq 0 ]
 then
     ARCH_TYPE="tar.lzma"
+fi
+
+echo "$FILENAME" | grep -e '^.*\.tar\.xz$' > /dev/null 2>&1
+if [ $? -eq 0 ]
+then
+    ARCH_TYPE="tar.xz"
 fi
 
 echo "$FILENAME" | grep -e '^.*\.tar\.7z$' > /dev/null 2>&1
diff --git a/_aipb_lddsums b/_aipb_lddsums
--- a/_aipb_lddsums
+++ b/_aipb_lddsums
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+if [ ! -d "$AIP_DIR" ]
+then
+    echo " SORRY: please, install aipsetup (if not yet),"
+    echo "        and run this from main program (aipsetup)"
+    echo " ERROR: AIP_DIR not set"
+    exit 1
+fi
+
 FILENAME="$1"
 WHICH=`which "$FILENAME" 2> /dev/null` 
 
diff --git a/aipsetup b/aipsetup
--- a/aipsetup
+++ b/aipsetup
@@ -3,11 +3,33 @@
 #this will be changed during 'make install'
 export AIP_DIR=""
 
-if [ ! -d "$AIP_DIR" ]
+if [ -z "$AIP_DIR" ]
 then
-    echo "\$AIP_DIR variable not set, please use 'make install' in the source directory"
+    echo " SORRY: \$AIP_DIR must be set by aipsetup installed in /usr/bin."
+    echo "        but it isn't set."
+    echo " ERROR: aipsetup not installed. reinstall please."
     exit 1
 fi
+
+if [ ! -f "$AIP_DIR/_aipb_checkaipinstallation" ]
+then
+    echo "file \"\$AIP_DIR/_aipb_checkaipinstallation\" not found"
+    if [ ! -r "$AIP_DIR/_aipb_checkaipinstallation" ]
+    then
+	echo "file \"\$AIP_DIR/_aipb_checkaipinstallation\" not readable"
+	exit 1
+    fi
+    exit 1
+fi
+
+bash "$AIP_DIR/_aipb_checkaipinstallation" ins
+if [ "$?" -ne 0 ]
+then
+    echo "some aipsetup installation error. reinstall please."
+    exit 1
+fi
+
+exit 0
 
 case "$#" in
     0)
